from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.formLayout = QtWidgets.QHBoxLayout()
        self.formLayout.setObjectName("formLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setObjectName("leftLayout")
        self.label_lineEditNama = QtWidgets.QLabel(self.centralwidget)
        self.label_lineEditNama.setObjectName("label_lineEditNama")
        self.leftLayout.addWidget(self.label_lineEditNama)
        self.lineEditNama = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNama.setObjectName("lineEditNama")
        self.leftLayout.addWidget(self.lineEditNama)
        self.label_spinBoxKalori = QtWidgets.QLabel(self.centralwidget)
        self.label_spinBoxKalori.setObjectName("label_spinBoxKalori")
        self.leftLayout.addWidget(self.label_spinBoxKalori)
        self.spinBoxKalori = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxKalori.setObjectName("spinBoxKalori")
        self.leftLayout.addWidget(self.spinBoxKalori)
        self.label_comboBoxKategori = QtWidgets.QLabel(self.centralwidget)
        self.label_comboBoxKategori.setObjectName("label_comboBoxKategori")
        self.leftLayout.addWidget(self.label_comboBoxKategori)
        self.comboBoxKategori = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxKategori.setObjectName("comboBoxKategori")
        self.leftLayout.addWidget(self.comboBoxKategori)
        self.checkBoxSehat = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxSehat.setObjectName("checkBoxSehat")
        self.leftLayout.addWidget(self.checkBoxSehat)
        self.sliderKenyang = QtWidgets.QSlider(self.centralwidget)
        self.sliderKenyang.setOrientation(QtCore.Qt.Horizontal)
        self.sliderKenyang.setObjectName("sliderKenyang")
        self.leftLayout.addWidget(self.sliderKenyang)
        self.label_sliderKenyang = QtWidgets.QLabel(self.centralwidget)
        self.label_sliderKenyang.setObjectName("label_sliderKenyang")
        self.leftLayout.addWidget(self.label_sliderKenyang)
        self.buttonTambah = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTambah.setObjectName("buttonTambah")
        self.leftLayout.addWidget(self.buttonTambah)
        self.formLayout.addLayout(self.leftLayout)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setObjectName("rightLayout")
        self.labelDaftar = QtWidgets.QLabel(self.centralwidget)
        self.labelDaftar.setObjectName("labelDaftar")
        self.rightLayout.addWidget(self.labelDaftar)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.rightLayout.addWidget(self.tableWidget)
        self.formLayout.addLayout(self.rightLayout)
        self.verticalLayout.addLayout(self.formLayout)
        self.labelTotalKalori = QtWidgets.QLabel(self.centralwidget)
        self.labelTotalKalori.setObjectName("labelTotalKalori")
        self.verticalLayout.addWidget(self.labelTotalKalori)
        self.labelIdentity = QtWidgets.QLabel(self.centralwidget)
        self.labelIdentity.setObjectName("labelIdentity")
        self.verticalLayout.addWidget(self.labelIdentity)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.labelTitle.setText(_translate("MainWindow", "NutriTrack – Hitung Kalori Harianmu"))
        self.label_lineEditNama.setText(_translate("MainWindow", "Nama Makanan:"))
        self.label_spinBoxKalori.setText(_translate("MainWindow", "Kalori (kkal):"))
        self.label_comboBoxKategori.setText(_translate("MainWindow", "Kategori:"))
        self.checkBoxSehat.setText(_translate("MainWindow", "Makanan Sehat"))
        self.label_sliderKenyang.setText(_translate("MainWindow", "Tingkat Kenyang:"))
        self.buttonTambah.setText(_translate("MainWindow", "Tambah Makanan"))
        self.labelDaftar.setText(_translate("MainWindow", "Daftar Makanan Hari Ini:"))
        self.labelTotalKalori.setText(_translate("MainWindow", "Total Kalori: 0 kkal"))
        self.labelIdentity.setText(_translate("MainWindow", "Nama: Cindy Aulia Rahmani | NIM: F1D022116"))
